### ISSUE TITLE
Cardinalities of LM and compression model don't match

### ISSUE THREAD

**Issue by jbmaxwell** [facebookresearch/audiocraft#235]
I'm trying to test training from scratch, using 48khz stereo audio, and I'm hitting the error: 
`AssertionError: ("Cardinalities of the LM and compression model don't match: ", 'LM cardinality is 2048 vs ', 'compression model cardinality is 1024')`

Where (or how) can I set the LM cardinality?

**Comment by jbmaxwell** [comment]
Okay, I found it in a yaml:

```
transformer_lm:
  n_q: 4
  card: 1024       # <-- Here!
 ```

Fixing this got me to a new error about number of codebooks which, digging around further, was connected to `n_q`. 
I fixed that and moved on to a new error:

```
File "/home/james/src/somms/audiocraft/audiocraft/modules/codebooks_patterns.py", line 334, in __init__
    assert len(self.delays) == self.n_q
AssertionError
```

I see this is connected to `codebooks_patterns.py`, but I'm not sure how to set this. More generally, does anybody know how to get an LM that will work with 48khz stereo from `Facebook/encodec_48khz`?

**Comment by jbmaxwell** [comment]
Okay, this _seems_ to be solved with:

```
codebooks_pattern:
  modeling: parallel
  delays: 16
```

New error: `ValueError: The input length is not properly padded for batched chunked decoding. Make sure to pad the input correctly.`

Is padding handled by the data provider or in the LM?

**Comment by jbmaxwell** [comment]
Okay, my audio is in ~44s segments, and it gets me one step (maybe) further using:

```
dataset:
  batch_size: 12  # 2 GPUs
  sample_on_weight: false  # Uniform sampling all the way
  sample_on_duration: false  # Uniform sampling all the way
  segment_duration: 1.0          # <--- this
  min_audio_duration: 1.0.      # <-- and this
```

but... new error: `AssertionError: Scaled compression model not supported with LM.`
