### ISSUE TITLE
Configuration for training with CLAP embeddings

### ISSUE THREAD

**Issue by jbm-somms** [facebookresearch/audiocraft#441]
I'm wondering if anyone has any configuration info they could share on training with CLAP embeddings?
I want to try the `laion/larger_clap_music` model from Huggingface, but it's really unclear to me how the project is supposed to be configured. 

Any help greatly appreciated.

**Comment by jbm-somms** [comment]
Just adding a bit more info, I managed to at least get to an _attempt_ to load `larger_clap_music` using this config:

```
conditioners:
  description:
    model: clap
    clap: # based on
      checkpoint: //reference/clap/larger_clap_music/pytorch_model.bin
      name: laion/larger_clap_music
      model_arch: 'HTSAT-base'
      enable_fusion: false
      sample_rate: 32000
      max_audio_length: 10
      audio_stride: 1
      dim: 512
      attribute: description
      normalize: true
      quantize: true  # use RVQ quantization
      n_q: 12
      bins: 1024
      kmeans_iters: 50
      text_p: 0.  # probability of using text embed at train time
      cache_path: null
  ```
  
  But it fails with a laundry list of "Unexpected key(s)"
  
  I also tried just pointing it to the folder (it complained that it was not a file) and the `config.json` inside the HF download (which gave some kind of parse error).
